### PR TITLE
Adding GitHub Asset

### PR DESCRIPTION
**Pull request by NathanK239486**
plugIn Add-on github to unity added. It's source can be found in the assets folder in Plugins. To open GitHub plugin window you can find it in the top left Window dropdown and select it. In this window you can push pull check history with easier access and convenience.

DON'T PUSH THIS, ITS NOTHING!

### CODE REVIEW

**Comment by SeanDarrah** [comment]
how about..... no

**Comment by NathanK239486** [comment]
shit... damn

**Comment by SeanDarrah** [comment]
lel get gud, ur not gamer enough

**Comment by NathanK239486** [comment]
:(

**Comment by NathanK239486** [comment]
I've reconsidered

**Pull request closed without merging**
